# Generated by Django 4.2 on 2023-08-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='access_level',
            field=models.CharField(choices=[('staff', 'staff'), ('system_admin', 'System Admin'), ('super_admin', 'Super Admin')], default='staff', max_length=20),
        ),
    ]
