# Generated by Django 4.2 on 2023-04-26 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='board_members/')),
                ('role', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mandate', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='members',
        ),
        migrations.AddField(
            model_name='department',
            name='charter',
            field=models.FileField(blank=True, null=True, upload_to='charters/'),
        ),
        migrations.AddField(
            model_name='department',
            name='mandate',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='department',
            name='performance_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='strategy',
            field=models.ImageField(blank=True, null=True, upload_to='strategies/'),
        ),
        migrations.AddField(
            model_name='department',
            name='vision',
            field=models.ImageField(blank=True, null=True, upload_to='visions/'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_performance_review', models.DateField(blank=True, default=None, null=True)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='core.section')),
            ],
        ),
    ]
