# Generated by Django 4.2 on 2023-04-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_staff_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='name',
        ),
    ]
