# Generated by Django 4.2 on 2023-04-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_staff_certifications_staff_last_performance_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='board_members/')),
                ('role', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
    ]
