# Generated by Django 4.2 on 2023-12-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_boardmember_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='performance_score',
        ),
        migrations.AddField(
            model_name='department',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='hod_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
