# Generated by Django 4.2 on 2023-12-04 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_department_vision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='vision',
            field=models.ImageField(blank=True, null=True, upload_to='visions/'),
        ),
    ]
