# Generated by Django 4.2 on 2023-04-24 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 12, 6, 59, 101296, tzinfo=datetime.timezone.utc)),
        ),
    ]
