# Generated by Django 4.2 on 2023-04-27 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_poll_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 4, 16, 36, 27, 703854, tzinfo=datetime.timezone.utc)),
        ),
    ]
