# Generated by Django 4.2 on 2023-08-31 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_alter_poll_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 12, 38, 23, 109371, tzinfo=datetime.timezone.utc)),
        ),
    ]
