# Generated by Django 4.2 on 2023-08-31 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_poll_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 7, 17, 13, 30, 625625, tzinfo=datetime.timezone.utc)),
        ),
    ]
