# Generated by Django 4.2 on 2023-12-05 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_alter_poll_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 8, 39, 8, 543095, tzinfo=datetime.timezone.utc)),
        ),
    ]
